# Generated by Django 3.1.3 on 2022-12-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='cif',
            new_name='ci',
        ),
    ]
