# Generated by Django 3.1.3 on 2022-12-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20221213_0928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trabajador',
            new_name='Empleado',
        ),
    ]
